### PR TITLE
Add unit conversion code to this calculator code

### LINKED ISSUE #18: Add unit conversion code to this calculator code
Add a feature to perform simple unit conversions (like meters to kilometers, Celsius to Fahrenheit, etc.). This can add a practical utility aspect to the calculator.

### PR DESCRIPTION
**Pull request by SachinSihag1407**
@sunny7899 

bug #18

### Feature Added: Unit Conversion Utility

This pull request enhances the calculator functionality by adding a feature for simple unit conversions, catering to practical utility needs. The following conversions have been implemented:

**- Meters to Kilometers:** Converts distance in meters to kilometers.
**- Celsius to Fahrenheit:** Converts temperature from Celsius to Fahrenheit.
**- Kilometers to Miles:** Converts distance in kilometers to miles.
**- Fahrenheit to Celsius:** Converts temperature from Fahrenheit to Celsius.

These additions not only expand the calculator's capabilities but also make it more versatile for everyday calculations. The user can now seamlessly perform mathematical operations alongside necessary unit conversions, making this tool more valuable and user-friendly.

### CODE REVIEW

**Comment by sunny7899** [comment]
@SachinSihag1407 i can't see these conversion

**Comment by SachinSihag1407** [comment]
@sunny7899   can you explain me in detail about what issue is there?

**Comment by sunny7899** [comment]
@SachinSihag1407 where is this code can you share screenshot
image

**Comment by SachinSihag1407** [comment]
@sunny7899 

### https://github.com/sunny7899/c-basic/pull/26

"Hello! I’m participating in Hacktoberfest as a beginner in open-source. Could you kindly review and consider accepting this pull request? It would really help me on my Hacktoberfest journey. Thank you for the opportunity to contribute!"

**Pull request closed without merging**
